[conda]
disabled = false
symbol = "ğŸ…’"

[env_var]
variable = "ENV_NAME"
prefix = ""
symbol = "ğŸŒ"

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 12
truncation_symbol = "â€¦"

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ "

[hostname]
ssh_only = true
prefix = "âŸª"
suffix = "âŸ«"
disabled = false

[kubernetes]
disabled = false
symbol = "âˆ "

[python]
disabled = false
