[package]
disabled = false

[conda]
disabled = false
symbol = "ğŸ…’Â·"
prefix = "("
suffix = ")"

[env_var]
variable = "ENV_NAME"
prefix = ""
symbol = "ğŸŒ "

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 12
truncation_symbol = ""

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[hostname]
ssh_only = true
prefix = "âŸª"
suffix = "âŸ«"
disabled = false

[kubernetes]
disabled = false
